/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pharmacymanagementsystem.GUI;

import java.awt.*;
import com.mycompany.pharmacymanagementsystem.DAO.*;
import com.mycompany.pharmacymanagementsystem.Model.*;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author maryamwaleed
 */
public class DeviceGUI extends javax.swing.JFrame {

    /**
     * Creates new form DeviceGUI
     */
    public DeviceGUI() {
        initComponents();
        populateItemID();
        getContentPane().setBackground(Color.decode("#FFFFFF")); 
        ImageIcon originalIcon = new ImageIcon("4.png");
        int labelWidth = Image.getWidth();
        int labelHeight = Image.getHeight();
        Image.setIcon(resizeImageIcon(originalIcon, labelWidth, labelHeight));

    }
    private SupplierDAO supplierDAO;
    private ImageIcon resizeImageIcon(ImageIcon icon, int width, int height) {
    Image img = icon.getImage();
    Image resizedImage = img.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
    return new ImageIcon(resizedImage);
   
    
}

    /**
     * Creates new form SupplierGUI
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCbDevID = new javax.swing.JComboBox<>();
        jTfModel = new javax.swing.JTextField();
        jTfDeviceT = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jBtnAdd = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jBtnShowAll = new javax.swing.JButton();
        jLblStatus = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(227, 217, 201));

        jPanel1.setBackground(new java.awt.Color(213, 217, 224));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLblTitle.setFont(new java.awt.Font("Big Caslon", 0, 18)); // NOI18N
        jLblTitle.setText("Device Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setBackground(new java.awt.Color(213, 217, 224));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(213, 217, 224));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel1.setText("Device ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel6.setText("Device Type");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel7.setText("Model");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jCbDevID.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jCbDevID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jCbDevID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 280, -1));

        jTfModel.setText(" ");
        jPanel2.add(jTfModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 280, -1));

        jTfDeviceT.setText(" ");
        jPanel2.add(jTfDeviceT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 280, -1));

        jPanel3.setBackground(new java.awt.Color(213, 217, 224));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnAdd.setBackground(new java.awt.Color(166, 201, 218));
        jBtnAdd.setFont(new java.awt.Font("Didot", 0, 13)); // NOI18N
        jBtnAdd.setText("Add");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnUpdate.setBackground(new java.awt.Color(166, 201, 218));
        jBtnUpdate.setFont(new java.awt.Font("Didot", 0, 13)); // NOI18N
        jBtnUpdate.setText("Update");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jBtnShowAll.setBackground(new java.awt.Color(166, 201, 218));
        jBtnShowAll.setFont(new java.awt.Font("Didot", 0, 13)); // NOI18N
        jBtnShowAll.setText("Show All");
        jBtnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowAllActionPerformed(evt);
            }
        });

        jLblStatus.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLblStatus.setText("Status: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnShowAll, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jBtnAdd)
                .addGap(18, 18, 18)
                .addComponent(jBtnUpdate)
                .addGap(18, 18, 18)
                .addComponent(jBtnShowAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Image.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed

        String selecetedID = (String) jCbDevID.getSelectedItem();
        String deviceTXT = jTfDeviceT.getText().trim();
        String model = jTfModel.getText().trim();
  
        if (model.isEmpty() || selecetedID.equals("--Select ID--") || deviceTXT.isEmpty()) {
            jLblStatus.setText("Please enter/select all required data!");
            return;
        }

        Device device = new Device(); // Create a new Medicine object
        device.setID(selecetedID);
        device.setDeviceType(deviceTXT);
        device.setModel(model);

        DeviceDAO deviceDAO = new DeviceDAO();
        try {
            int insertStatus = deviceDAO.addDevice(device);

            if (insertStatus > 0) {
                jLblStatus.setText("Device " + selecetedID + " has been successfully added!");
            } else {
                jLblStatus.setText("Failed to add Device " + selecetedID);
            }
        } catch (SQLException e) {
            jLblStatus.setText("Database Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
         String selecetedID = (String) jCbDevID.getSelectedItem();
        String deviceTXT = jTfDeviceT.getText().trim();
        String model = jTfModel.getText().trim();
  
        if (model.isEmpty() || selecetedID.equals("--Select ID--") || deviceTXT.isEmpty()) {
            jLblStatus.setText("Please enter/select all required data!");
            return;
        }

        Device device = new Device(); // Create a new device object
        device.setID(selecetedID);
        device.setDeviceType(deviceTXT);
        device.setModel(model);

        DeviceDAO deviceDAO = new DeviceDAO();
        try {
            int updateStatus = deviceDAO.updateDevice(device);

            if (updateStatus > 0) {
                jLblStatus.setText("Device " + selecetedID + " has been successfully Updated!");
            } else {
                jLblStatus.setText("Failed to Update Device " + selecetedID);
            }
        } catch (SQLException e) {
            jLblStatus.setText("Database Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jBtnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShowAllActionPerformed
        // TODO add your handling code here:
        loadAllDevices();
    }//GEN-LAST:event_jBtnShowAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeviceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeviceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeviceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeviceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeviceGUI().setVisible(true);
            }
        });
    }
        
private final void populateItemID() {
    //I SHOULD SELECT ONLY MEDICINES!
    try {
        ItemDAO itemDAO = new ItemDAO();
        java.util.List<Device> iList = itemDAO.getAllDevices(); 
        String[] defaultOption = new String[]{"--Select ID--"};
        jCbDevID.setModel(new DefaultComboBoxModel<>(defaultOption));
        for (Item i : iList) {
            jCbDevID.addItem(i.getID());
        }
    } catch (SQLException sqlex) {
        jLblStatus.setText(sqlex.getMessage());
    }
}

      private final void loadAllDevices() {
    Vector colNameV = new Vector();
    colNameV.add("Device ID");
    colNameV.add("Device Name");
    colNameV.add("Device Type");
    colNameV.add("Device Model");
    //Step 2: set the rows of jtable
    DeviceDAO deviceDAO = new DeviceDAO();
    java.util.List<Device> dList = null; // Initialize a list to store item data
    try {
        dList = deviceDAO.getAllDevices(); // Call get all from the DAO
    } catch (SQLException e) {
        jLblStatus.setText("Database Error! " + e.getMessage());
    }

    Vector rowDataVector = new Vector(); // Initialize a vector to store row data
    // Iterate through each item in the iList
    for (Device d : dList) {
        Vector<Object> cellVector = new Vector<>(); // Initialize cellVector for each item
        cellVector.add(d.getID());
        cellVector.add(d.getName());
        cellVector.add(d.getDeviceType());
        cellVector.add(d.getModel());
         rowDataVector.add(cellVector);  //creates the vector row, by adding each cell in the row
        }      
        //initlize the JTable instance using the row data and column data vectors
        jTable1=new JTable(rowDataVector,colNameV);
        jScrollPane1.setViewportView(jTable1);
}
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnShowAll;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JComboBox<String> jCbDevID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLblStatus;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTfDeviceT;
    private javax.swing.JTextField jTfModel;
    // End of variables declaration//GEN-END:variables
}
