/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pharmacymanagementsystem.GUI;
import com.mycompany.pharmacymanagementsystem.DAO.*;
import com.mycompany.pharmacymanagementsystem.Model.Supplier;
import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import java.awt.*;
import java.util.Map;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;




/**
 *
 * @author maryamwaleed
 */
public class InsightsGUI extends javax.swing.JFrame {

    /**
     * Creates new form InsightsGUI
     */
  private InsightsDAO insightsDAO;
  private ImageIcon resizeImageIcon(ImageIcon icon, int width, int height) {
    Image img = icon.getImage();
    Image resizedImage = img.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
    return new ImageIcon(resizedImage);
   
    
}
// Usage in your constructor or wherever you set the image
 public InsightsGUI() {
    initComponents();
    getContentPane().setBackground(Color.decode("#FFFFFF")); 
    populateComboBox();
    createChart(); // Add this line to create the chart

    ImageIcon originalIcon = new ImageIcon("5.png");
    int labelWidth = Image.getWidth();
    int labelHeight = Image.getHeight();
    Image.setIcon(resizeImageIcon(originalIcon, labelWidth, labelHeight));
    
    insightsDAO = new InsightsDAO();
    try {
        int totalPrescriptions = insightsDAO.getTotalPrescriptions();
        jTotalP.setText(String.valueOf(totalPrescriptions) + " Prescriptions. ");

        // Get most prescribed items
        List<List<Object>> mostPrescribedItems = insightsDAO.getMostPrescribedItems();

        // Clear existing rows in the table model
        DefaultTableModel model = (DefaultTableModel) jItemTbl.getModel();
        model.setRowCount(0);

        // Populate the table
        model.setColumnIdentifiers(new Object[] {"Item ID", "Prescription Count"});
        for (List<Object> itemData : mostPrescribedItems) {
            model.addRow(new Object[] { itemData.get(0), itemData.get(1) });
        }
    } catch (SQLException e) {
        jTotalP.setText("Error: " + e.getMessage());
    }
    
    // Wrap jPanel5 inside a JScrollPane
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblTitle = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jCbSupplier = new javax.swing.JComboBox<>();
        jLblStatus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jItemTbl1 = new javax.swing.JTable();
        jSearchBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTotalP = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jItemTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(213, 217, 224));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLblTitle.setFont(new java.awt.Font("Big Caslon", 0, 18)); // NOI18N
        jLblTitle.setText("Insights Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        Image.setText(" ");
        getContentPane().add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 180));

        jPanel5.setBackground(new java.awt.Color(213, 217, 224));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 510, 430));

        jPanel3.setBackground(new java.awt.Color(213, 217, 224));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLblStatus.setFont(new java.awt.Font("Big Caslon", 0, 13)); // NOI18N
        jLblStatus.setText("Status:");

        jLabel4.setFont(new java.awt.Font("Big Caslon", 1, 13)); // NOI18N
        jLabel4.setText("The Total items supplied by supplier");

        jItemTbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jItemTbl1);

        jSearchBTN.setBackground(new java.awt.Color(166, 201, 218));
        jSearchBTN.setFont(new java.awt.Font("Big Caslon", 0, 13)); // NOI18N
        jSearchBTN.setText("Search");
        jSearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jSearchBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(371, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchBTN))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jPanel2.setBackground(new java.awt.Color(213, 217, 224));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Big Caslon", 1, 13)); // NOI18N
        jLabel1.setText("The Total Number of Prescriptions");

        jTotalP.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jTotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 290, 330));

        jPanel4.setBackground(new java.awt.Color(213, 217, 224));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Big Caslon", 1, 13)); // NOI18N
        jLabel2.setText("The Total Most prescribed Items:");

        jItemTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jItemTbl);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchBTNActionPerformed
        // TODO add your handling code here:
            String selectedSupplierId = (String) jCbSupplier.getSelectedItem();
    if (selectedSupplierId != null && !selectedSupplierId.isEmpty()) {
        try {
            // Get items by supplier
            List<Object> itemsBySupplier = insightsDAO.getItemsBySupplier(selectedSupplierId);
            
            // Clear existing rows in the table model
            DefaultTableModel supplierModel = (DefaultTableModel) jItemTbl1.getModel();
            supplierModel.setRowCount(0);
            
            // Set column names
            supplierModel.setColumnIdentifiers(new Object[] {"Item ID", "Item Name", "Category", "Supplier ID", "Supplier Name"});
            
            // Populate the table
            for (Object rowData : itemsBySupplier) {
                supplierModel.addRow((Object[]) rowData);
            }
        } catch (SQLException ex) {
            jLblStatus.setText("Error: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_jSearchBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsightsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsightsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsightsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsightsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsightsGUI().setVisible(true);
            }
        });
    }
    /*
     private void createChart() {
    try {
        InsightsDAO insightsDAO = new InsightsDAO();

        // Retrieve data from InsightsDAO
        Map<String, Integer> inventoryDistribution = insightsDAO.getInventoryDistributionByCategory();

        // Create dataset
        DefaultPieDataset dataset = new DefaultPieDataset();
        for (Map.Entry<String, Integer> entry : inventoryDistribution.entrySet()) {
            dataset.setValue(entry.getKey(), entry.getValue());
        }

        // Create chart
        JFreeChart chart = ChartFactory.createPieChart(
                "Inventory Items by Category",
                dataset,
                true,
                true,
                false
        );

        // Create chart panel
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(400, 300));

        // Create a panel to hold the chart
        JPanel chartPanelContainer = new JPanel();
        chartPanelContainer.setLayout(new BorderLayout());
        chartPanelContainer.add(chartPanel, BorderLayout.CENTER);

        // Add chart panel container to the jPanel5
        jPanel5.setLayout(new BorderLayout());
        jPanel5.add(chartPanelContainer, BorderLayout.CENTER);
    } catch (SQLException e) {
        // Handle SQLException
        e.printStackTrace();
    }
}*/
    private void createChart() {
    try {
        InsightsDAO insightsDAO = new InsightsDAO();

        // Retrieve data from InsightsDAO
        Map<String, Integer> inventoryDistribution = insightsDAO.getInventoryDistributionByCategory();

        // Create dataset
        DefaultPieDataset dataset = new DefaultPieDataset();
        for (Map.Entry<String, Integer> entry : inventoryDistribution.entrySet()) {
            dataset.setValue(entry.getKey(), entry.getValue());
        }

        // Create chart
        JFreeChart chart = ChartFactory.createPieChart(
                "Inventory Items by Category",
                dataset,
                true,
                true,
                false
        );

        // Customize label generator for pie sections
        PiePlot plot = (PiePlot) chart.getPlot(); // Cast the plot to PiePlot
        plot.setForegroundAlpha(0.5f); // Adjust transparency
        plot.setLabelGenerator(new StandardPieSectionLabelGenerator("{0}: {1} ({2})"));

        // Create chart panel
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(400, 300));

        // Create a panel to hold the chart
        JPanel chartPanelContainer = new JPanel();
        chartPanelContainer.setLayout(new BorderLayout());
        chartPanelContainer.add(chartPanel, BorderLayout.CENTER);

        // Add chart panel container to the jPanel5
        jPanel5.setLayout(new BorderLayout());
        jPanel5.add(chartPanelContainer, BorderLayout.CENTER);
    } catch (SQLException e) {
        // Handle SQLException
        e.printStackTrace();
    }
}



    
    
private final void populateComboBox() {
    try {
        SupplierDAO supplierDAO = new SupplierDAO();
        List<Supplier> sList = supplierDAO.getAllSupplier(); 
        String[] defaultOption = new String[]{"--Select Supplier--"};
        jCbSupplier.setModel(new DefaultComboBoxModel<>(defaultOption));
        for (Supplier s : sList) {
            jCbSupplier.addItem(s.getId());
        }
    } catch (SQLException sqlex) {
        jLblStatus.setText(sqlex.getMessage());
    }
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JComboBox<String> jCbSupplier;
    private javax.swing.JTable jItemTbl;
    private javax.swing.JTable jItemTbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblStatus;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSearchBTN;
    private javax.swing.JLabel jTotalP;
    // End of variables declaration//GEN-END:variables
}
