/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pharmacymanagementsystem.GUI;

import java.awt.Color;
import java.sql.SQLException;
import com.mycompany.pharmacymanagementsystem.Model.*;
import com.mycompany.pharmacymanagementsystem.DAO.*;
import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author maryamwaleed
 */
public class Login extends javax.swing.JFrame {
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        getContentPane().setBackground(Color.decode("#D5D9E0")); 
        ImageIcon originalIcon = new ImageIcon("b1.png");
        int labelWidth = Image.getWidth();
        int labelHeight = Image.getHeight();
        Image.setIcon(resizeImageIcon(originalIcon, labelWidth, labelHeight));
        
    }
    private ImageIcon resizeImageIcon(ImageIcon icon, int width, int height) {
    Image img = icon.getImage();
    Image resizedImage = img.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
    return new ImageIcon(resizedImage);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelPass = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jTextFieldPass1 = new javax.swing.JPasswordField();
        jLabelInfo = new javax.swing.JLabel();
        jLblTitle = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        jLblTitle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelUsername.setFont(new java.awt.Font("Big Caslon", 0, 14)); // NOI18N
        jLabelUsername.setText("Username :");

        jTextFieldUsername.setFont(new java.awt.Font("Big Caslon", 0, 14)); // NOI18N
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });

        jLabelPass.setFont(new java.awt.Font("Big Caslon", 0, 14)); // NOI18N
        jLabelPass.setText("Password :");

        jButtonLogin.setBackground(new java.awt.Color(0, 102, 153));
        jButtonLogin.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jTextFieldPass1.setFont(new java.awt.Font("Big Caslon", 0, 14)); // NOI18N

        jLabelInfo.setFont(new java.awt.Font("Big Caslon", 0, 14)); // NOI18N
        jLabelInfo.setForeground(new java.awt.Color(255, 0, 51));
        jLabelInfo.setText(" ");

        jLblTitle.setFont(new java.awt.Font("Didot", 1, 16)); // NOI18N
        jLblTitle.setText("Sign in to your account");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelUsername)
                            .addComponent(jLabelPass)
                            .addComponent(jTextFieldUsername)
                            .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabelPass)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 360, 470));

        Image.setText(" ");
        getContentPane().add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 400, 470));

        jLblTitle1.setFont(new java.awt.Font("Didot", 1, 24)); // NOI18N
        jLblTitle1.setText("Pharmacy Management System");
        getContentPane().add(jLblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 380, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
          String supplierID = jTextFieldUsername.getText().trim();
    String password = jTextFieldPass1.getText().trim();

    // Check if the username and password fields are empty
    if (supplierID.isEmpty() || password.isEmpty()) {
        jLabelInfo.setText("Enter credentials!");
    } else {
        try {
            // Attempt to retrieve the user's information from the database
            SupplierDAO supplierDAO = new SupplierDAO();
            Supplier supplier = supplierDAO.findSupplierById(supplierID);

            if (supplier != null) {
                // Compare the retrieved password with the one entered by the user
                if (supplier.getPassword().equals(password)) {
                    // Login successful, only allow Supplier GUI
                    new SupplierGUI().setVisible(true);
                    this.dispose(); // Close the Login window
                } else {
                    // Passwords don't match, display error message
                    jLabelInfo.setText("Incorrect password!");
                }
            } else if ("admin".equals(supplierID) && "admin12".equals(password)) {
                // Login as admin, open MainGUI
                new MainGUI().setVisible(true);
                this.dispose(); // Close the Login window
            } else {
                // User not found, display error message
                jLabelInfo.setText("User not found!");
            }
        } catch (SQLException ex) {
            // Handle database error
            jLabelInfo.setText("Database error occurred!");
            ex.printStackTrace();
        }
    }
    
 
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JLabel jLblTitle1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jTextFieldPass1;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
