/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pharmacymanagementsystem.GUI;
import java.awt.*;
import java.sql.SQLException;
import com.mycompany.pharmacymanagementsystem.Model.*;
import com.mycompany.pharmacymanagementsystem.DAO.*;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author maryamwaleed
 */
public class SupplierGUI extends javax.swing.JFrame {

    private SupplierDAO supplierDAO;
    private ImageIcon resizeImageIcon(ImageIcon icon, int width, int height) {
    Image img = icon.getImage();
    Image resizedImage = img.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
    return new ImageIcon(resizedImage);
   
    
}

    /**
     * Creates new form SupplierGUI
     */
    public SupplierGUI() {
        initComponents();
        getContentPane().setBackground(Color.decode("#FFFFFF")); 
    ImageIcon originalIcon = new ImageIcon("s.png");
    int labelWidth = Image.getWidth();
    int labelHeight = Image.getHeight();
    Image.setIcon(resizeImageIcon(originalIcon, labelWidth, labelHeight));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTfID = new javax.swing.JTextField();
        jTfName = new javax.swing.JTextField();
        jTfInfo = new javax.swing.JTextField();
        jTfIPass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jBtnAdd = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jBtnShowAll = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jBtnDelete1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSupplier = new javax.swing.JTable();
        Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(213, 217, 224));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLblTitle.setFont(new java.awt.Font("Big Caslon", 1, 18)); // NOI18N
        jLblTitle.setText("Supplier Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(213, 217, 224));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel1.setText("Supplier ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("Supplier Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jTfID.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTfID.setText(" ");
        jTfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfIDActionPerformed(evt);
            }
        });
        jPanel2.add(jTfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 32, 272, 30));

        jTfName.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTfName.setText(" ");
        jPanel2.add(jTfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 270, 30));

        jTfInfo.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTfInfo.setText(" ");
        jTfInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfInfoActionPerformed(evt);
            }
        });
        jPanel2.add(jTfInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 270, 30));

        jTfIPass.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTfIPass.setText(" ");
        jTfIPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfIPassActionPerformed(evt);
            }
        });
        jPanel2.add(jTfIPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 270, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel6.setText("Contact Info:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jPanel3.setBackground(new java.awt.Color(213, 217, 224));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnAdd.setBackground(new java.awt.Color(166, 201, 218));
        jBtnAdd.setFont(new java.awt.Font("Didot", 0, 13)); // NOI18N
        jBtnAdd.setText("Add Supplier");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnUpdate.setBackground(new java.awt.Color(166, 201, 218));
        jBtnUpdate.setFont(new java.awt.Font("Didot", 0, 13)); // NOI18N
        jBtnUpdate.setText("Update Supplier");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jBtnShowAll.setBackground(new java.awt.Color(166, 201, 218));
        jBtnShowAll.setFont(new java.awt.Font("Didot", 0, 13)); // NOI18N
        jBtnShowAll.setText("Show All Suppliers");
        jBtnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowAllActionPerformed(evt);
            }
        });

        jLabelStatus.setText("Status:");

        jBtnDelete1.setBackground(new java.awt.Color(166, 201, 218));
        jBtnDelete1.setFont(new java.awt.Font("Didot", 0, 13)); // NOI18N
        jBtnDelete1.setText("Delete Supplier");
        jBtnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnShowAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelStatus))
                    .addComponent(jBtnDelete1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jBtnAdd)
                .addGap(18, 18, 18)
                .addComponent(jBtnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnDelete1)
                .addGap(10, 10, 10)
                .addComponent(jBtnShowAll)
                .addGap(28, 28, 28)
                .addComponent(jLabelStatus)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTableSupplier.setBackground(new java.awt.Color(213, 217, 224));
        jTableSupplier.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTableSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSupplier);

        Image.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed

        String SupplierID = jTfID.getText().trim();
        String SupplierName = jTfName.getText().trim();
        String SupplierInfo = jTfInfo.getText().trim();
        String SupplierPass = jTfIPass.getText().trim();
        

        if (SupplierID.isEmpty() || SupplierName.isEmpty() || SupplierInfo.isEmpty() || SupplierPass.isEmpty()) {
            // display an error message
            jLabelStatus.setText("Please enter data");
            //exit the program
            return;
        }
        
           SupplierDAO supplierDAO=new SupplierDAO();
       //before adding the program, make sure that the SupplierID doesn't exist in the database
       
            try{
                if(supplierDAO.findSupplierById(SupplierID) !=null){
                jLabelStatus.setText("Code exists in the DB");
                return;
                }
                
                //add a new program
                int insertStatus=supplierDAO.addNewSupplier(SupplierID, SupplierName, SupplierInfo, SupplierPass);
                jLabelStatus.setText("Supplier "+SupplierID+" is added!");
                loadAllSupplier();
                
                }
        catch(SQLException e){
            jLabelStatus.setText(e.getMessage());
         
                }

       
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
    
       // Read input data from text fields
    String supplierID = jTfID.getText().trim();
    String supplierName = jTfName.getText().trim();
    String supplierInfo = jTfInfo.getText().trim();

if (supplierID.isEmpty() || supplierName.isEmpty() || supplierInfo.isEmpty()) {
    // Display an error message
    jLabelStatus.setText("Please enter data");
    // Exit the program
    return;
}

SupplierDAO supplierDAO = new SupplierDAO();
// Before updating the supplier, make sure that the ID exists in the database

int updateStatus = -1;
try {
    Supplier existingSupplier = supplierDAO.findSupplierById(supplierID);
    if (existingSupplier == null) {
        jLabelStatus.setText("Supplier does not exist in the DB");
        return;
    }
    
    // Update the supplier
    updateStatus = supplierDAO.updateSupplier(supplierID, supplierName, supplierInfo);

    if (updateStatus == 1) {
        jLabelStatus.setText("Supplier " + supplierID + " is updated!");
        // Reload all suppliers
        loadAllSupplier();
    } else {
        jLabelStatus.setText("No record is updated");
    }
} catch (SQLException e) {
    jLabelStatus.setText("Database Error: " + e.getMessage());
}

        
        
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jBtnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShowAllActionPerformed
        // TODO add your handling code here:
        loadAllSupplier();
    }//GEN-LAST:event_jBtnShowAllActionPerformed

    private void jTfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfIDActionPerformed

    private void jTfInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfInfoActionPerformed

    private void jBtnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelete1ActionPerformed
        // TODO add your handling code here:
        
        // Get the supplier ID from the text field and remove leading/trailing whitespace
    String supplierID = jTfID.getText().trim();
    
    // Check if the supplier ID is empty
    if (supplierID.isEmpty()) {
        // Display an error message if the ID is empty
        jLabelStatus.setText("Please enter the ID of the supplier to delete");
        return; // Exit the method if the ID is empty
    }
    
    // Create an instance of SupplierDAO to interact with the database
    SupplierDAO supplierDAO = new SupplierDAO();
    int deleteStatus = -1; // Initialize delete status
    
    try {
        // Check if the supplier with the given ID exists in the database
        if (supplierDAO.findSupplierById(supplierID) == null) {
            jLabelStatus.setText("Supplier ID does not exist in the DB");
            return; // Exit the method if the supplier doesn't exist
        }
        
        // Delete the supplier from the database
        deleteStatus = supplierDAO.deleteSupplier(supplierID);
    } catch (SQLException e) {
        // Handle any SQL exceptions by displaying the error message
        jLabelStatus.setText("Database Error: " + e.getMessage());
    }
    
     // Check if the delete operation was successful
    if (deleteStatus == 1) {
        // Display success message if the supplier is deleted
        jLabelStatus.setText("Supplier " + supplierID + " has been successfully deleted!");
        // Clear the text fields
        jTfID.setText("");
        jTfName.setText("");
        jTfInfo.setText("");
        // Reload all suppliers to reflect the changes
        loadAllSupplier();
    } else {
        // Display error message if there was an error while deleting the supplier
        jLabelStatus.setText("Failed to delete Supplier " + supplierID);
    }
    
    }//GEN-LAST:event_jBtnDelete1ActionPerformed

    private void jTfIPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfIPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfIPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierGUI().setVisible(true);
            }
        });
    }
    
    
    
    
      private final void loadAllSupplier() {
    // Step 1: Set the column names of the JTable
        Vector colNameV = new Vector();
        colNameV.add("Supplier ID");
        colNameV.add("Supplier Name");
        colNameV.add("Contact Info");

        // Step 2: Set the rows of the JTable

        // 2.a Retrieve all supplier data
        SupplierDAO supplierDAO = new SupplierDAO();
        java.util.List<Supplier> sList = null; // Initialize a list to store supplier data
        try {
            sList = supplierDAO.getAllSupplier(); // Call getAllSupplier from the DAO to retrieve all suppliers
        } catch (SQLException e) {
            // Handle any SQL exceptions by displaying the error message
            jLabelStatus.setText("Database Error! " + e.getMessage());
        }

        Vector rowDataVector = new Vector(); // Initialize a vector to store row data

        // Iterate through each supplier in the sList
        for (Supplier s : sList) {
            Vector<Object> cellVector = new Vector<>(); // Initialize cellVector for each supplier
            cellVector.add(s.getId()); // Add Supplier ID to cellVector
            cellVector.add(s.getName()); // Add Supplier Name to cellVector
            cellVector.add(s.getContactInfo()); // Add Contact Info to cellVector
            rowDataVector.add(cellVector); // Add cellVector to rowDataVector to create the vector row
        }      

        //Initialize the JTable instance using the row data and column data vectors
            jTableSupplier = new JTable(rowDataVector, colNameV);
            jScrollPane1.setViewportView(jTableSupplier);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnDelete1;
    private javax.swing.JButton jBtnShowAll;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSupplier;
    private javax.swing.JTextField jTfID;
    private javax.swing.JTextField jTfIPass;
    private javax.swing.JTextField jTfInfo;
    private javax.swing.JTextField jTfName;
    // End of variables declaration//GEN-END:variables

  
    }

